apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-1.0-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-1.0
  template:
    metadata:
      labels:
        app: demo-1.0
    spec:
      containers:
        - name: demo-1.0
          image: nizarbsalem/hello-word-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-1.0-service
spec:
  selector:
    app: demo-1.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
